import "./App.css";
import { Galary } from "./Galary";

function App() {
  let cardGalary = [
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading2",
      subhead: "Sub heading2",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading4",
      subhead: "Sub heading",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading5",
      subhead: "Sub heading2",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading6",
      subhead: "Sub heading3",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading7",
      subhead: "Sub heading3",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading8",
      subhead: "Sub heading",
      colors: "Blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading9",
      subhead: "Sub heading2",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading10",
      subhead: "Sub heading3",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading2",
      subhead: "Sub heading2",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading2",
      subhead: "Sub heading2",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading4",
      subhead: "Sub heading",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading5",
      subhead: "Sub heading2",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading6",
      subhead: "Sub heading3",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading7",
      subhead: "Sub heading3",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading8",
      subhead: "Sub heading",
      colors: "Blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading9",
      subhead: "Sub heading2",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading10",
      subhead: "Sub heading3",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading2",
      subhead: "Sub heading2",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading2",
      subhead: "Sub heading2",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading4",
      subhead: "Sub heading",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading5",
      subhead: "Sub heading2",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading6",
      subhead: "Sub heading3",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading7",
      subhead: "Sub heading3",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading8",
      subhead: "Sub heading",
      colors: "Blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading9",
      subhead: "Sub heading2",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading10",
      subhead: "Sub heading3",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading2",
      subhead: "Sub heading2",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading2",
      subhead: "Sub heading2",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading4",
      subhead: "Sub heading",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading5",
      subhead: "Sub heading2",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading6",
      subhead: "Sub heading3",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading7",
      subhead: "Sub heading3",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading8",
      subhead: "Sub heading",
      colors: "Blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading9",
      subhead: "Sub heading2",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading10",
      subhead: "Sub heading3",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading2",
      subhead: "Sub heading2",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading2",
      subhead: "Sub heading2",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading4",
      subhead: "Sub heading",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading5",
      subhead: "Sub heading2",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading6",
      subhead: "Sub heading3",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading7",
      subhead: "Sub heading3",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading8",
      subhead: "Sub heading",
      colors: "Blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading9",
      subhead: "Sub heading2",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading10",
      subhead: "Sub heading3",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading2",
      subhead: "Sub heading2",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading2",
      subhead: "Sub heading2",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading4",
      subhead: "Sub heading",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading5",
      subhead: "Sub heading2",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading6",
      subhead: "Sub heading3",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading7",
      subhead: "Sub heading3",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading8",
      subhead: "Sub heading",
      colors: "Blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading9",
      subhead: "Sub heading2",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading10",
      subhead: "Sub heading3",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading2",
      subhead: "Sub heading2",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading2",
      subhead: "Sub heading2",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading4",
      subhead: "Sub heading",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading5",
      subhead: "Sub heading2",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading6",
      subhead: "Sub heading3",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading7",
      subhead: "Sub heading3",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading8",
      subhead: "Sub heading",
      colors: "Blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading9",
      subhead: "Sub heading2",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading10",
      subhead: "Sub heading3",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading2",
      subhead: "Sub heading2",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading2",
      subhead: "Sub heading2",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading4",
      subhead: "Sub heading",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading5",
      subhead: "Sub heading2",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading6",
      subhead: "Sub heading3",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading7",
      subhead: "Sub heading3",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading8",
      subhead: "Sub heading",
      colors: "Blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading9",
      subhead: "Sub heading2",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading10",
      subhead: "Sub heading3",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading2",
      subhead: "Sub heading2",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading2",
      subhead: "Sub heading2",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading4",
      subhead: "Sub heading",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading5",
      subhead: "Sub heading2",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading6",
      subhead: "Sub heading3",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading7",
      subhead: "Sub heading3",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading8",
      subhead: "Sub heading",
      colors: "Blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading9",
      subhead: "Sub heading2",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading10",
      subhead: "Sub heading3",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading2",
      subhead: "Sub heading2",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading2",
      subhead: "Sub heading2",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading4",
      subhead: "Sub heading",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading5",
      subhead: "Sub heading2",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading6",
      subhead: "Sub heading3",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading7",
      subhead: "Sub heading3",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading8",
      subhead: "Sub heading",
      colors: "Blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading9",
      subhead: "Sub heading2",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading10",
      subhead: "Sub heading3",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading2",
      subhead: "Sub heading2",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading2",
      subhead: "Sub heading2",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading4",
      subhead: "Sub heading",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading5",
      subhead: "Sub heading2",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading6",
      subhead: "Sub heading3",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading7",
      subhead: "Sub heading3",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading8",
      subhead: "Sub heading",
      colors: "Blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading9",
      subhead: "Sub heading2",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading10",
      subhead: "Sub heading3",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading2",
      subhead: "Sub heading2",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading2",
      subhead: "Sub heading2",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading4",
      subhead: "Sub heading",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading5",
      subhead: "Sub heading2",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading6",
      subhead: "Sub heading3",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading7",
      subhead: "Sub heading3",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading8",
      subhead: "Sub heading",
      colors: "Blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading9",
      subhead: "Sub heading2",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading10",
      subhead: "Sub heading3",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading2",
      subhead: "Sub heading2",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading2",
      subhead: "Sub heading2",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading4",
      subhead: "Sub heading",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading5",
      subhead: "Sub heading2",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading6",
      subhead: "Sub heading3",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading7",
      subhead: "Sub heading3",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading8",
      subhead: "Sub heading",
      colors: "Blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading9",
      subhead: "Sub heading2",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading10",
      subhead: "Sub heading3",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading2",
      subhead: "Sub heading2",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading2",
      subhead: "Sub heading2",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading4",
      subhead: "Sub heading",
      colors: "orange",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading5",
      subhead: "Sub heading2",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading6",
      subhead: "Sub heading3",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading7",
      subhead: "Sub heading3",
      colors: "blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading8",
      subhead: "Sub heading",
      colors: "Blue",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading9",
      subhead: "Sub heading2",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading10",
      subhead: "Sub heading3",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "green",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading2",
      subhead: "Sub heading2",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading3",
      subhead: "Sub heading3",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
    {
      heading: "Heading1",
      subhead: "Sub heading",
      colors: "Chartreuse",
      para: "Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.Lorem ipsum dolor sit amet. Qui optio sint ut similique accusamus sed placeat.",
    },
  ];
  return (
    <div className="App">
      <h2 style={{fontSize:"3vw"}}>Card Galary Using Functon Compenent</h2>
      <Galary finalarray={cardGalary} />
    </div>
  );
}

export default App;
